package org.example.model.Enum;

public enum Pos {
    ADJECTIVE,
    ADVERB,
    AUXILIARY_VERB,
    CONJUNCTION,
    DEFINITE_ARTICLE,
    DETERMINER,
    EXCLAMATION,
    INDEFINITE_ARTICLE,
    INFINITIVE_MARKER,
    LINKING_VERB,
    MODAL_VERB,
    NOUN,
    NUMBER,
    ORDINAL_NUMBER,
    PREPOSITION,
    PRONOUN,
    VERB,
    ALL
}

